version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            pip install --user -U flake8==3.7.1
            python -m flake8 --show-source pythia/

  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Install dependencies
          command: |
            export PATH=$PATH:$HOME/.local/bin
            pip install -U virtualenv --user
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -U pip==19
            pip install -U codecov
            pip install -U -e . -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run -m unittest discover tests/ -v
            coverage report -i
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5

#  test-deploy-pypi:
#    docker:
#      - image: circleci/python:3.7
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run:
#          name: test-deploy-pypi
#          command: |
#            pip install --user -U -r requirements.txt
#            bash .test-deploy.bash
#
#  deploy-pypi:
#    docker:
#      - image: circleci/python:3.7
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run:
#          name: deploy-pypi
#          command: |
#            pip install --user -U -r requirements.txt
#            bash .deploy.bash


workflows:
  version: 2
  test:
    jobs:
      - style-check
      - test-3.5:
          requires:
            - style-check
      - test-3.6:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
#      - test-deploy-pypi:
#          filters:
#            branches:
#              only: /release\/.*/
#          requires:
#            - test-3.5
#            - test-3.6
#            - test-3.7
#  deploy:
#    jobs:
#      - deploy-pypi:
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /v.*/
